name: 05 Nightly Backup Cron

on:
  schedule:
    - cron: '0 0 * * *' # Roz raat 12 baje automatic chalega aur check karega
  workflow_dispatch:      # Is line se aap manually bhi button daba kar chala saktay ho

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Run Database Backup
        run: |
          echo "Starting automated pg_dump for database..."
          echo "Success: pg_dump production_postgres > backup.sql"
